pipeline {
    agent any

    stages {

        stage('Test') {
            steps {
                bat 'node --version'
            }
        }

        stage('Deploy') {
            steps {
                bat 'kubectl apply -f deployment.yml'
            }
        }

    }
}