pipeline {
    agent any

    stages {

        stage('Compile') {
            steps {
                dir('practiceSet/Question3') {
                    bat 'mvn compile'
                }
            }
        }

        stage('Test') {
            steps {
                dir('practiceSet/Question3') {
                    bat 'mvn test'
                }
            }
        }

        stage('Package') {
            steps {
                dir('practiceSet/Question3') {
                    bat 'mvn package'
                }
            }
        }

        stage('Docker Build') {
            steps {
                dir('practiceSet/Question3') {
                    bat 'docker build -t app:v1 .'
                }
            }
        }

        stage('Docker Tag') {
            steps {
                bat 'docker tag app:v1 gaurious/app:v1'
            }
        }

        stage('Docker Push') {
            steps {
                bat 'docker push gaurious/app:v1'
            }
        }
    }

    post {
        always {
            junit '**/target/surefire-reports/*.xml'
        }
    }
}