version: "3.8"

services:
  backend:
    image: node:20
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    networks:
      - app-network
  mongodb:
    image: mongo

    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network: