pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                dir('practiceSet/FinalQuestions/Question9/myapp') {
                    bat 'mvn clean compile'
                }
            }
        }
        stage('Test') {
            steps {
                dir('practiceSet/FinalQuestions/Question9/myapp') {
                    bat 'mvn test'
                }
                
            }
        }

        stage('Package') {
            steps {
                dir('practiceSet/FinalQuestions/Question9/myapp') {
                    bat 'mvn package'
                }
                
            }
        }
        stage('Docker Build') {
            steps {
                dir('practiceSet/FinalQuestions/Question9/myapp') {
                    bat 'docker build -t gaurious/question9-app:v1 .'
                }
                
            }
        }
        stage('Docker Push') {
            steps {
                dir('practiceSet/FinalQuestions/Question9/myapp') {
                    bat 'docker push gaurious/question9-app:v1'
                }
                
            }
        }
    }
}